.. _adding-your-first-instrument:

4. Adding your first Instrument
================================

Click on ``+ Add new Instrument`` button (either one), and the following dialog comes up:

.. image:: images/RsIc-add_new_instrument.drawio.png

We add a typical LAN instrument with HiSLIP interface. If you wish to switch the session type to VXI-11 or USB-TMC, do so with the tab selector on the left side.

Enter the IP Address or the computer name and hit the **Test** button. We are lucky, our instrument connection worked, the plugin fills out all other fields for us:

.. image:: images/RsIc-add_new_instrument_success.drawio.png

**Name**, **Alias**, **Icon Picture** come pre-filled with the values parsed from the instrument's IDN response:

	- **Name** - has to be unique in your list of instruments.	
	- **Alias** - in your case ``smw``, you are going to reference your instrument from python scripts.
	- **Family** - non-editable field, it is set according the internal table to specify the family of your instrument.
	- **Comment** - add custom comment/note to this instrument.

.. hint::
    You can use the same **Alias** by multiple instruments, but only one can be set to active. The reason is practical - you can quickly switch between different connection types for your ``smw``, without changing anything in your python script.
    Change the active/inactive status with the button **Instrument Active**. Inactive instruments work just like the active ones, except of SCPI auto-completion in your python scripts. There, the SCPI auto-completion relates only to the currently active instruments.

.. tip::
    If your LAN connection does not work, try to use the **Ping** button to see whether the instrument is available on LAN.
    Searching for LAN instruments only works in certain scenarios. If your instrument does not appear in the found list, it does not necessary mean that it is not available.
    The Search feature is very helpful with USB-TMC instruments, where it finds all of them:

    .. image:: images/RsIc-instrument_search_usbtmc.drawio.png

.. _instr_config_advanced_options:

**Advanced Options** button allows you select additional settings for your session, like VISA selection (we hope you use R&S VISA :-), VISA Timeout, Logging mode, etc... :

.. image:: images/RsIc-additional_session_settings.drawio.png

You can also adjust the icon picture or even add your own custom picture with the button **Select Icon** (or single-click on the current icon picture).
If possible, use the format 640x480:

.. image:: images/RsIc-select_icon.drawio.png

.. note::
    Settings in this configuration dialog results in a Python code snippet for RsInstrument that you can copy to clipboard by hitting the button **Copy Constructor Code**.
    Then, use it in your python script to initialize connection to your instrument:

    .. code-block:: python

        smw = RsInstrument('TCPIP::10.102.52.42::hislip0', reset=False, options='SelectVisa = rs, VisaTimeout = 3000')
