8. Function Panel - Hardcopy
=============================

Hardcopy is a function that captures content of the instrument's screen. Our plugin offers that with one click (OK, it could be up to three clicks :-).

.. image:: images/FunctionPanel_Hardcopy.drawio.png

Description of the controls:

1. **Function Panel Hardcopy Tab** - select this tab to access Hardcopy features.
2. **Make Screenshot Button** - requires active connection (see SCPI Communicator). If connected, this button starts the screenshot acquisition and transfer to your computer.
3. **Save to File Button** - available after the successful screenshot acquisition, allows saving the picture in **jpg** or **png** format and original size.
4. **Copy to Clipboard Button** - copies the file to Clipboard in original size.
5. **Fit to View** - automatically performed after the successful screenshot acquisition. Adjust the picture size to fit the view with limited width or height. Does the zoom > 1:1 too.
6. **Show in Original Size** - changes the picture back to the original size and activates the view pane's scroll controls if necessary.
7. **Go Automatically to Local Afterwards** - after the screenshot is finished, the instrument goes to local.
8. **Auto File Naming** - if checked, you do not need to enter new name by each "Save", you only enter it once, and the further ones are then auto-named with name suffix indexes _001, _002, _003 and so on...





