6. Instrument Tool Window
==========================

Instrument Tool Window (**ITW**) provides all the features available for the instrument:

.. image:: images/RsIcITW-instrument_tool_window.drawio.png

Info Panel
"""""""""""

The **Info Panel** is a header for the Instrument Tool Window. It contains all the essential information about your instrument.

.. hint::
    - **Right-click** on the instrument's icon to get its context-menu, same as in the overview list.
    - **Left-click** on the on the instrument's icon to open its Configuration Window.

.. _scpi-communicator:

SCPI Communicator
""""""""""""""""""

SCPI Communicator contains controls for connecting and communicating with your instrument. The connection status is valid for all other functionalities in the ITW.

.. image:: images/RsIcITW-comm_panel.drawio.png

Description of the controls:

1. **Connection Button** - toggle button for connecting and disconnecting to the instrument. When connected, multiple functions of the ITW become available. Right-click allows for sending GoToLocal or GoToRemote signal, Reset or setting VISA Timeout.
2. **Go-to-Local** - button for the instrument to go to local mode.
3. **Go-to-Remote** - button for the instrument to go to remote mode.
4. **Instrument error checking** - toggle instrument error checking after each command.
5. **Visit Home Page Button** - go to your instrument's home web address. Available for instruments with LAN connection and working webserver.
6. **SCPI Logger Toggle** - opens/closes SCPI Logger Tool Window. The Logger logs entire communication with your instrument coming from the plugin, and optionally from your python script (for that, you need to `switch on logging to UDP <https://rsinstrument.readthedocs.io/en/latest/StepByStepGuide.html#logging>`_)
7. **Paste import and constructor snippet** - pastes an RsInstrument import statement, plus the instrument's constructor snippet to your currently opened python script.
8. **Commands History** - keeps list of all the commands used in the past. Invoke the quick version of the window by pressing **UP** key in the SCPI Command Field. The full version you can invoke by pressing **DOWN** in the SCPI Command Field (10).
9. **Favorite Commands** - mark your commands as favorite with the left-click or open the Favorites window with the right-click.
10. **Multi-line SCPI Editor** - open this popup window to manage multiple lines of SCPI commands. :any:`See below <itw_multi_line_scpi_editor>`.
11. **SCPI Command Drag Button** - drag the SCPI command to your script or to another editor. On drop, you can decide to insert plain string or SCPI call snippet.
12. **SCPI Command Field with Auto-completion** - write your SCPI command here. If your instrument has a SCPI Tree available (see :ref:`7. Function Panel - SCPI Tree`), this field offers you auto-completion for SCPI commands.
13. **Communication Action Button** - sends/queries the current SCPI command (Field 12) to the instrument. The button changes its function based on the command type (write/query). RsIC automatically recognizes binary response, and the result display changes accordingly. You can also select the mode with the Field 11 - see the tip below.
14. **More Options** - select the type of write/query action - standard, with OPC, query binary data. The setting is persistent. You can also select whether you want to see two separate buttons for Write and Query.
15. **SCPI Response Field** - text field that contains responses received from the instrument.
16. **SCPI Response Field Resizer** - change the height of the response field to fit your needs.
17. **Response Info** - shows additional response information. For text, it shows its length and if commas are detected, it counts number of elements.
18. **Save Binary Response to File** - this button is enabled when you have received a binary response from the instrument.
19. **Copy Response to Clipboard** - enabled when the SCPI Response Field (Field 12) is non-empty.

.. tip::
    You can configure the look-and-feel of the Communicator in :any:`settings_instrument_tool_windows`

.. hint::
    The **Connect/Disconnect Button** (1) has a right-click context menu with additional features:

    .. image:: images/RsIcITW-connect_button_context_menu.drawio.png

.. note::
    If your SCPI Query reads a binary block, the response display changes to show binary data:

    .. image:: images/RsIcITW-binary_response.drawio.png


Commands History
"""""""""""""""""

Each command you send to your instrument is stored in a persistent history, which is grouped by the instrument's family. That means, that for example, both SMW200A and SMM100A share the same history and favorite commands, because they both belong to the family of Vector Signal Generators. The Commands History window has two versions: **Quick** and **Full**. You can invoke the quick version by pressing **UP** key while typing in the **SCPI Command Field** (12). Quick version has the last command sent at the bottom:

.. image:: images/RsIcITW-cmds_history_quick.drawio.png

Full Version is invoked with **DOWN** or clicking on **Commands History** button (8). The last command sent is at the top. Full version allows you to edit the list with drag and drop or **DELETE** key. Pressing **ENTER** or double-clicking sends the command to the instrument. Dragging a command to you opened Python script inserts the call snippet. If you want to drag more than one command, use the **Right Mouse Button**. You can pin the window to prevent it from auto-closing:

.. image:: images/RsIcITW-cmds_history_full.drawio.png

Favorite Commands
""""""""""""""""""

You can mark any command of the instrument as favorite to have a quick access to it by clicking the star icon on the Communication Panel (9). To open the Favorites Window, right-click the star icon:

.. image:: images/RsIcITW-open_cmds_favorites.drawio.png

Edit, add, or delete the commands from the list:

.. image:: images/RsIcITW-cmds_favorites.drawio.png

.. _itw_multi_line_scpi_editor:

Multi-line SCPI Editor
"""""""""""""""""""""""""""""

Multi-line SCPI Editor is a standard Pycharm Text editor, but with a special top panel for execution and parse controls. It overcomes the limitation of a single-line SCPI Command field.
The SCPI Editor is in detailed described in :any:`plain_scpi_scripts`.

Open the Multi-Line SCPI Editor:

.. image:: images/RsIcITW-multi_line_open.drawio.png

The three **Command Banks** serve as 3 different scripts that you can switch between. Multi-line SCPI Editor GUI:

.. image:: images/RsIcITW-multi_line_scpi_cmds.drawio.png

The file is always related to the instrument’s ITW. Its content is not saved in a scpi file. Instead, you have three command banks that you can switch between and use them practically as three different files. The entire content is persistent and is stored in the plugin XML file.